name: Publicar Pagina a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Instala Surge
        run: npm install --global surge

      - name: Publicar pagina
        run: surge --project ./ --domain ErlynValerio20220413.surge.sh --token ${{ secrets.SURGE_API_KEY }}
